### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Toxin#10]
Встречается устаревший синтаксис градиентов:
![image](https://user-images.githubusercontent.com/85496220/121334002-f6ffe000-c921-11eb-9ec1-94393366157e.png)

Встречаются табы вперемешку с пробелами:
![image](https://user-images.githubusercontent.com/85496220/121335611-6aeeb800-c923-11eb-87c3-cf05070e05d2.png)

Не единообразное написание цветов в HEX формате. Не принципиальный момент, однако последовательный код проще читается.
![image](https://user-images.githubusercontent.com/85496220/121338432-2c0e3180-c926-11eb-8a65-8b0a92d6a820.png)

**Comment by webproject67** [comment]
[#10](https://github.com/webproject67/Toxin/issues/10) [updated](https://github.com/webproject67/Toxin/pull/14)

**Comment by romansilivestrov** [comment]
### colors-type.scss:23

![image](https://user-images.githubusercontent.com/85496220/123506956-98e83200-d66f-11eb-96d7-7cc84387054c.png)

Возможно, тут лучше сделать через модификаторы.

**Comment by webproject67** [comment]
[#10](https://github.com/webproject67/Toxin/issues/10) [updated](https://github.com/webproject67/Toxin/pull/23)
