### ISSUE TITLE
Интерфейс

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Toxin#11]
Для текстовых инпутов всё же лучше оставить текстовый курсор.
![image](https://user-images.githubusercontent.com/85496220/121341054-f585e600-c928-11eb-9d73-11f2c498a2ec.png)

Дропдауны и датапикеры следует закрывать при клике вне элемента.

Нет полей у узкого датапикера.
![image](https://user-images.githubusercontent.com/85496220/121341875-c1f78b80-c929-11eb-95bb-44e711d13c26.png)

Подразумевается, что поле дата рождения (masked field) фильтрует инпут и позволяет вводить только валидные даты согласно маске ДД.ММ.ГГГГ. Также поле должно автоматически форматировать вводимую дату (расставлять точки).
![image](https://user-images.githubusercontent.com/85496220/121343313-367efa00-c92b-11eb-96fe-992028781848.png)

Чекбоксы переключаются при клике на пустое пространство, такого быть не должно:
![image](https://user-images.githubusercontent.com/85496220/121344238-33383e00-c92c-11eb-8cee-a5233e1e907b.png)

**Comment by webproject67** [comment]
[#11](https://github.com/webproject67/Toxin/issues/11) [updated](https://github.com/webproject67/Toxin/pull/16)

**Comment by romansilivestrov** [comment]
### Курсор

>Для текстовых инпутов всё же лучше оставить текстовый курсор.

А для выпадающих списков и других интерактивных элементов следует использовать [cursor: pointer](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.9)

![image](https://user-images.githubusercontent.com/85496220/122801775-3983ce00-d2cd-11eb-8525-ee70b3844247.png)

### Content overflow

Кнопка не имеет горизонтальных отступов и текст может наезжать на иконку:
![image](https://user-images.githubusercontent.com/85496220/122802519-1dccf780-d2ce-11eb-8eb4-a3364fde4582.png)

![image](https://user-images.githubusercontent.com/85496220/122802769-6be1fb00-d2ce-11eb-8ec0-bbac9f585f2b.png)

![image](https://user-images.githubusercontent.com/85496220/122802936-aa77b580-d2ce-11eb-84d4-0c3378d964ce.png)

### Дата рождения

Дата всё еще не проверяется на валидность:

![image](https://user-images.githubusercontent.com/85496220/122803228-00e4f400-d2cf-11eb-88f8-5e988bbbb975.png)

### Datepicker

При клике на стрелки и выбор года/месяца датапикер закрывается:

![image](https://user-images.githubusercontent.com/85496220/122803762-b87a0600-d2cf-11eb-89c2-3d32a13cac3c.png)

### Rich checkbox

Переключается при клике на пустое место:

![image](https://user-images.githubusercontent.com/85496220/122803976-fb3bde00-d2cf-11eb-86af-8a9a8e06a519.png)

**Comment by webproject67** [comment]
[#11](https://github.com/webproject67/Toxin/issues/11) [updated](https://github.com/webproject67/Toxin/pull/18)

**Comment by romansilivestrov** [comment]
### Datepicker

![image](https://user-images.githubusercontent.com/85496220/123506768-a94bdd00-d66e-11eb-8635-e0243e7e265b.png)

Всё ещё не вижу боковых отступов у узкого датапикера.

**Comment by webproject67** [comment]
[#11](https://github.com/webproject67/Toxin/issues/11) [updated](https://github.com/webproject67/Toxin/pull/22)
