### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Toxin#12]
![image](https://user-images.githubusercontent.com/85496220/121345112-2536ed00-c92d-11eb-8148-0f41f0e28164.png)

В данном случае не надо типизировать `$value`. Метод `html()` возвращает и принимает его как `string`. Тут следует менять именно подчёркнутые строки, чтобы они возвращали правильный тип.

https://github.com/airbnb/javascript#type-casting--coercion

**Comment by webproject67** [comment]
[#12](https://github.com/webproject67/Toxin/issues/12) [updated](https://github.com/webproject67/Toxin/pull/15)
