### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Toxin#17]
### Code style

Js в pug следуёт форматировать согласно [code](https://github.com/airbnb/javascript#whitespace--in-brackets) [style](https://github.com/airbnb/javascript#whitespace--in-braces):

![image](https://user-images.githubusercontent.com/85496220/122805300-984b4680-d2d1-11eb-9638-fc8b77836bc7.png)
![image](https://user-images.githubusercontent.com/85496220/122805719-1dcef680-d2d2-11eb-918c-f05559511158.png)

### Conditionals

![image](https://user-images.githubusercontent.com/85496220/122809408-c0897400-d2d6-11eb-889e-03fa0efd8f11.png)

Я так понимаю, что `color` - это строка? В таком случае тернарное выражение ни к чему, можно сделать так:

```pug
ul(class=`checkbox__list ${listClassName}`)
```

Можно также упростить использование миксина, если, например, передавать не полный доп. класс, а лишь модификатор и использовав [логическое И](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND):

```pug
mixin example({colorMod = ''})
  .example(class=classMod && `example_color_${colorMod}`)
```

### Param destructuring

![image](https://user-images.githubusercontent.com/85496220/122806714-53281400-d2d3-11eb-9d45-5d616b718f79.png)

Здесь всё хорошо, но можно пойти дальше, деструктурировав параметр options не отходя от скобок;) также при деструктурировании можно задавать значения по умолчанию:

```pug
mixin checkbox({ checkboxs, listClassName, color = '' })
```

### Mixins

Заметил места, где несколько миксинов в одном файле (checkbox, input, form etc.) - такого желательно избегать. Следует разделить их по блокам: 1 блок БЭМ - 1 миксин. Вспомогательные миксины можно вынести во внешний файл в директории блока, например, `helpers.pug`.

### Pages

`form-elements`, `headers-footers` и т. д. - это всё-таки страницы, а находятся в директории рядом с блоками. Возможно, стоит перенести весь их код в pages?

**Comment by webproject67** [comment]
[#17](https://github.com/webproject67/Toxin/issues/17) [updated](https://github.com/webproject67/Toxin/pull/19)

**Comment by romansilivestrov** [comment]
![image](https://user-images.githubusercontent.com/85496220/123506148-6805fe00-d66b-11eb-8896-7f697bf58ed8.png)

Вызов миксина выглядит довольно устрашающе:) Возможно, стоит выносить подобные большие объекты в константы, чтобы улучшить читаемость. Константы в свою очередь было бы неплохо держать в отдельном файле, pugjs поддерживает импорт из json. Назвать файл можно, например, `mixin-name.data.json`.

**Comment by webproject67** [comment]
[#17](https://github.com/webproject67/Toxin/issues/17) [updated](https://github.com/webproject67/Toxin/pull/21)
