### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Toxin#25]
https://github.com/webproject67/Toxin/blob/113e93db9992c215a3352d5ac66ecf4d46d6fb79/src/styles/scaffolding.scss#L23
Не должно быть заданных общих стилей для элементов, с использованием классов или тега, так как нарушается независимость блоков, блоки должны быть не зависимыми, чтобы можно было переносить блоки между проектами и везде  этот блок выглядел одинаково. Допускается глобальное задание стилей для html и body и задание свойства box-sizing, остальные элементы должны стилизоваться только внутри блока.

**Comment by Azmodan95** [comment]
Еще осталось классы .font-h2 и т.п.

**Comment by Azmodan95** [comment]
И еще такая штука есть: https://github.com/webproject67/Toxin/blob/c21cb5870e6b00886b839915535ea4e1b97fcc5c/src/pug/blocks/button-link/button-link.pug#L18
Когда в одном блоке встречаются другие блоки, то есть button-link и button-link2 это два разных блока.

**Comment by webproject67** [comment]
[#25](https://github.com/webproject67/Toxin/issues/25) [updated](https://github.com/webproject67/Toxin/pull/34)

**Comment by Azmodan95** [comment]
Появилось две проблемы, первая это то что пропал сам блок, к примеру как тут
https://github.com/webproject67/Toxin/blob/71005d7e6d742438678e6ecee7006041a3893b95/src/pug/blocks/advantage/advantage.pug#L4
сразу идет элемент, тогда должно быть `ul.advantage`
А вторая это то что теперь для стилизации используются отдельные блоки, а не модификаторы. То есть одна сущность button-link, сейчас представлена в виде трех отдельных блоков, что неверно, [тут](https://ru.bem.info/methodology/quick-start/#%D0%B1%D0%BB%D0%BE%D0%BA) можно посмотреть что из себя должен представлять блок.

**Comment by webproject67** [comment]
В issue Повторяющийся код 'И зачем создавать обертку div если для нее ни какие стили не применяются? ' Пришлось удалить, которые не применяются стили. 
В issue БЭМ 'Когда в одном блоке встречаются другие блоки, то есть button-link и button-link2 это два разных блока.' Пришлось разбить, создать несколько блоков

**Comment by Azmodan95** [comment]
> В issue Повторяющийся код 'И зачем создавать обертку div если для нее ни какие стили не применяются? ' Пришлось удалить, которые не применяются стили.
Нужно было удалить обертку и перенести блок на дочерний элемент. То есть на примере блока advantage, нужно было убрать div.advantage, и сделать элемент ul.advantage__list блоком ul.advantage, ну и соответственно все стили которые были на элементе advantage__list перенести на блок advantage.
> В issue БЭМ 'Когда в одном блоке встречаются другие блоки, то есть button-link и button-link2 это два разных блока.' Пришлось разбить, создал 3 блока разных, отличается классом
Да совершенно верно button-link и button-link2 это два разных блока. Но я не писал что надо их разделять, я имел в виду что подобное не верно, в одном блоке не могут присутствовать элементы других блоков. Нужно было исправить это не разделяя их на отдельные блоки.

**Comment by webproject67** [comment]
[#25](https://github.com/webproject67/Toxin/issues/25) [updated](https://github.com/webproject67/Toxin/pull/41)

**Comment by Azmodan95** [comment]
Проблема с button-link и button-link2 все еще осталась. Так я подозреваю что проблема по всей видимости в стилях, но это проблема решается добавление дополнительных модификаторов, а не созданием дополнительного блока. Можно сделать как-то так:
```
mixin button(options)
  -
    const { text, href, type, theme, color, size, state } = options;

    const typeModifiers = {
      button: 'button_type_button',
      submit: 'button_type_submit',
      link: 'button_type_link',
    };
    const themeModifiers = {
      filled: 'button_theme_filled',
      bordered: 'button_theme_bordered',
    };
    const colorModifiers = {
      gray: 'button_color_gray',
    };
    const sizeModifiers = {
      compact: 'button_size_compact',
    };
    const stateModifiers = {
      hovering: 'button_hovering',
    };
    const classes = [
      typeModifiers[type],
      sizeModifiers[size],
      themeModifiers[theme],
      colorModifiers[color],
      stateModifiers[state],
    ];
    const tag = type === 'link' ? 'a' : 'button';
    const buttonType = type === 'link' && typeModifier;
  #{tag}.button(type=buttonType, name=name, value=value, class=classes, href=href)= text
```
И стили:
```
.button {
  display: flex;
  align-items: center;
  justify-content: center;

  padding: 12px 18px;

  border: none;
  border-radius: 22px;

  font-weight: bold;
  font-size: 12px;
  line-height: 15px;
  text-decoration: none;
  text-transform: uppercase;
  color: $color-purple;

  transition: all 0.4s ease;

  cursor: pointer;

  &:hover,
  &_hovering {
    opacity: 0.5;
  }

  &_type {
    &_submit {
      position: relative;

      width: 100%;

      &::after {
        position: absolute;
        right: 10px;
        content: 'arrow_forward';
        font-family: 'MaterialIcons';
        font-weight: normal;
        font-size: 24px;
        line-height: 24px;
        text-transform: lowercase;
      }
    }
  }

  &_theme {
    &_filled,
    &_bordered {
      border: 2px solid transparent;

      background-image: linear-gradient(
          rgba(255, 255, 255, 0),
          rgba(255, 255, 255, 0)
        ),
        linear-gradient(180deg, #bc9cff 0%, #8ba4f9 100%);
      background-origin: border-box;
      background-clip: content-box, border-box;
    }
    &_filled {
      color: #fff;
    }

    &_bordered {
      box-shadow: 2px 1000px 1px #fff inset;
    }
  }

  &_color {
    &_gray {
      color: $color;
    }
  }

  &_size {
    &_compact {
      padding: 7px 18px;
    }
  }
}
```
Возможно что-то надо будет подправить, но думаю направление понятно.

---

Так же есть проблема с модификаторами, посмотри какие могут быть [типы модификаторов](https://ru.bem.info/methodology/quick-start/#%D1%82%D0%B8%D0%BF%D1%8B-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2), если используется модификатор ключ-значение то значение должно от ключа отделяться нижним подчеркиванием.

**Comment by webproject67** [comment]
[#25](https://github.com/webproject67/Toxin/issues/25) [updated](https://github.com/webproject67/Toxin/pull/45)

**Comment by Azmodan95** [comment]
https://github.com/webproject67/Toxin/blob/b5e2be8cac2fc75735ba78f483296cf034f702b3/src/pug/blocks/button/button.pug#L21
Что это за модификатор такой?) Есть ведь уже модификатор hovering, если нужно переопределить его значение в зависимости от темы можно использовать комбинированные селекторы
```
&_theme_bordered#{&}_hovering {
  opacity: 0.5;
}

&_theme_filled#{&}_hovering {
  color: #ffffff;
}
```

**Comment by Azmodan95** [comment]
https://github.com/webproject67/Toxin/blob/b5e2be8cac2fc75735ba78f483296cf034f702b3/src/pug/pages/headers-footers/headers-footers.pug#L11
Здесь похожая проблема, что уже была, для стилизации используются разные блоки, а не модификаторы.

**Comment by Azmodan95** [comment]
https://github.com/webproject67/Toxin/blob/b5e2be8cac2fc75735ba78f483296cf034f702b3/src/pug/pages/index/index.pug#L17
Еще такой момент есть, идет сразу элемент, а где сам блок потерялся?

**Comment by webproject67** [comment]
Интересный способ, даже в документации такого примера нету
` #{tag}.button(type=buttonType, class=classes, href=href)= text`
`&_theme_bordered#{&}_hovering `

Не обязательно модификаторы стилизовать, можно блоки и элементы, примеры с бэм

![1_yhXB1cpz2PS8qnbmtZ5d0Q](https://user-images.githubusercontent.com/34152979/134770105-6bf510d3-f94b-4547-890d-b4e347a28b59.jpeg)
![kFetIbKxQdABHhUecbic45Il0Bg](https://user-images.githubusercontent.com/34152979/134770126-41d07620-9df9-4b83-ab03-75229c101edd.png)

Ранее убрал блок, писал же что зачем блоки если стили не применяются, вернул)

[#25](https://github.com/webproject67/Toxin/issues/25) [updated](https://github.com/webproject67/Toxin/pull/48)

**Comment by Azmodan95** [comment]
> Не обязательно модификаторы стилизовать, можно блоки и элементы, примеры с бэм

Да все верно, в данном случае я ошибся с формулировкой я имел в виду элемент, а не блок. Так как было 4 элемента, и только у одного отличались стили, более правильно было бы создать один элемент, и где изменяются стили там назначить модификатор. То есть я имел в виду, что вместо block1..block4, нужно было сделать просто block, в данном случае вообще можно отказаться от модификатора, а использовать селектор вида `headers-footers__block:not(:first-child)`, либо можно заменить margin-top на margin-bottom.

> Ранее убрал блок, писал же что зачем блоки если стили не применяются, вернул)

Я о блоках ничего не писал, там было об обертках) На случай вот таких вот моментов, Виктор должен был дать мой телеграмм, если что-то не понятно или кажется странным можешь задавать вопросы, так как может возникнуть какое-то недопонимание, я могу ошибиться с формулировкой, это будет даже плюсом и сэкономит время.

---

Еще хочу заметить что с модификаторами все еще присутствуют проблемы, если модификатор не булевый он должен быть в формате ключ_значение
https://github.com/webproject67/Toxin/blob/1178bb85fc7b09f041051e6a111e03bdab6ba93c/src/pug/pages/colors-type/colors-type.pug#L25
В данном случае ключ отсутствует, вообще элементом ведь является не сам цвет, а квадрат, цвет выступает его модификатором, можно сделать как-то так:
```
colors-type__square_color_darkest-gray
colors-type__square_color_dark-gray
colors-type__square_color_gray
colors-type__square_color_light-gray
colors-type__square_color_lightest-gray
```

---

Еще момент у каждой страницы лучше сделать собственные стили.
