### ISSUE TITLE
Стандарты

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Toxin#26]
https://github.com/webproject67/Toxin/blob/113e93db9992c215a3352d5ac66ecf4d46d6fb79/src/pug/blocks/button-like/button-like.pug#L6
По стандартам кампании использование примесей не допускается [4.5](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.5), для стилизации нужно использовать модификаторы. Но тут еще достаточно странное использование, в миксин передаются стили относящиеся к самому блоку, а это уже не примесь, но тут не что ни мешает передать класс другого блока, по сути мы абсолютно любой класс можем передать, подобного быть не должно. В данном случае в active можно передать булевое значение и уже в самом блоке добавлять класс в зависимости от значения.

**Comment by webproject67** [comment]
[#26](https://github.com/webproject67/Toxin/issues/26) [updated](https://github.com/webproject67/Toxin/pull/32)
