### ISSUE TITLE
Повторяющийся код

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Toxin#27]
https://github.com/webproject67/Toxin/blob/113e93db9992c215a3352d5ac66ecf4d46d6fb79/src/pug/blocks/footer/footer.pug#L16
Здесь присутствует повторяющийся код, чтобы этого избежать можно использовать массив, и уже в цикле создавать нужное количество элементов.

**Comment by webproject67** [comment]
[#27](https://github.com/webproject67/Toxin/issues/27) [updated](https://github.com/webproject67/Toxin/pull/30)

**Comment by Azmodan95** [comment]
В компоненте button-link теперь появился повторяющийся код, но тут еще есть проблема, сейчас передается linkClassName и в зависимости от его значения добавляются нужные классы, но исходя из названия можно предположить что туда имя класса должно передаваться, лучше передавать значения из которых явно будет понятно какие значения можно установить. Зачем вообще модификатор hovering? Есть же псевдокласс :hover, который и используется сейчас вместе с модификатором. И зачем создавать обертку div если для нее ни какие стили не применяются?  К примеру можно сделать как-то так:
```
    const { text, href, theme, color, size } = options;

    const themeModifiers = {
      filled: 'button-link_theme_filled',
      bordered: 'button-link_theme_bordered',
    };
    const colorModifiers = {
      purple: 'button-link_color_purple',
    };
    const sizeModifiers = {
      compact: 'button-link_size_compact',
    };
    const classes = [
      'button-link',
      themeModifiers[theme], 
      colorModifiers[color], 
      sizeModifiers[size]
    ];

  a(class=classes href=href)= text
```
Еще заметил что обычную кнопку сейчас создать нельзя, можно модифицировать этот код для того чтобы можно было создать и обычную кнопку можно сюда же добавить и кнопку submit которая сейчас отдельно: 
```
    const { text, href, type, theme, color, size } = options;

    const themeModifiers = {
      filled: 'button_theme_filled',
      bordered: 'button_theme_bordered',
    };
    const colorModifiers = {
      purple: 'button_color_purple',
    };
    const sizeModifiers = {
      compact: 'button_size_compact',
    };
    const typeModifier = {
      submit: 'button_type_submit',
    };
    const classes = [
      'button',
      themeModifiers[theme], 
      colorModifiers[color], 
      sizeModifiers[size]
    ];

    const tag = type === 'link' ? 'a' : 'button';
    const buttonType = type === 'link' && type;

  #{tag}(type=buttonType class=classes href=href)=text
```
Стрелку можно повесить на модификатор button_type_submit, с помощью псевдоэлемент и свойство content уже прописать arrow_forward. И насчет js кода у блока с кнопкой sumbit, ни какого js кода у кнопки вообще быть не должно, если он только не связан с ее внешним видом. Если нам нужно какие-то действия сделать при отправке формы, то это нужно делать уже в самой форме на событие onsubmit

**Comment by webproject67** [comment]
![111](https://user-images.githubusercontent.com/34152979/131257692-c64aa21f-47fe-4822-8503-84ada670758c.PNG)

Разделил, создал 3 блока.


![Снимок](https://user-images.githubusercontent.com/34152979/131257308-7df7392d-5e61-40a3-b5e8-025b2871c80f.PNG)
Модификатор hovering для form elements, будто курсор находится внутри элемента.
[#27](https://github.com/webproject67/Toxin/issues/27) [updated](https://github.com/webproject67/Toxin/pull/36)
