### ISSUE TITLE
Установка зависимостей

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Toxin#28]
Сейчас на последней LTS версии nodejs зависимости не устанавливаются, судя по всему из-за версии node-sass, есть какая-то причина использовать node-sass? Почему не обычный [sass](https://www.npmjs.com/package/sass)? В обычном sass подобных проблем вроде нету.

**Comment by webproject67** [comment]
У меня windows 7, node v12.22.4, если установить node v14, выдает ошибку. 
![Снимок](https://user-images.githubusercontent.com/34152979/128846964-d0d949c3-f5ee-41ae-a51e-03358c6638e5.PNG)
Заменил node-sass на sass.
[#28](https://github.com/webproject67/Toxin/issues/28) [updated](https://github.com/webproject67/Toxin/pull/29)
