### ISSUE TITLE
Инициализация плагинов

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Toxin#33]
Нужно отделить инициализацию от реализации, они не должны находится в одном файле, можно в блоке создать файл init.js, в котором и будет происходить инициализация. И инициализация и реализация должна быть единообразная.
Так же насчет сторонних плагинов, их нужно через npm устанавливать, если же он там отсутствуют то можно создать папку lib и туда их перенести, в папке с блоками их быть не должно. И они кстати не должны как-то модифицироваться.

**Comment by webproject67** [comment]
[#33](https://github.com/webproject67/Toxin/issues/33) [updated](https://github.com/webproject67/Toxin/pull/35)

**Comment by Azmodan95** [comment]
Все еще инициализация и реализация находятся в одном файле. То есть на примере button-like, к реализации будет относиться изменение значения на кнопке, установка обработчика событий, а инициализация это нахождение всех dom элементов и инициализация плагина для них. И так же неплохо было бы реализацию обернуть в класс, который будет принимать dom элемент и уже с ним работать.

**Comment by webproject67** [comment]
Если често, я не понимаю зачем делить инициализацию и реализацию, впервые такое, прошлый раз разделил свой код и библиотеку. Google ничего такого не нашел, если не трудно, пришли пожалуйста ссылку материалы, я не представляю как должен выглядеть, неплохо бы примеры посмотреть

**Comment by Azmodan95** [comment]
Неужели все сторонние плагины которые сейчас используются при их импорте сразу происходит инициализация? Либо во втором проекте, при импорте плагина он сразу инициализируется? 
Собственно в чем тут проблема, как нам этим управлять? Что если нам понадобится различная функциональность, как в этом случае нам прокинуть настройки чтобы не дублировать код? Что если нам нужно будет инициализировать плагин в определенный момент? Или если мы захотим его использовать в разных частях приложения, с различными dom элементами? Плагины должны быть как минимум должны быть созданы с помощью функций конструкторов ну или классов это более современный синтаксис. Если интересует именно как должны разрабатываться плагины для jQuery, то [тут](https://www.smashingmagazine.com/2011/10/essential-jquery-plugin-patterns/) можно почитать об этом.
На чистом js на примере button-like можно как-то так сделать:
```
class ButtonLike {
  private element: HTMLElement;

  constructor(element: HTMLElement) {
    this.element = element;
  }

  public init() {
    this.initEvents();
  }

  private initEvents() {
    this.element.addEventListener('click', this.handleButtonLikeClick);
  }

  private handleButtonLikeClick = () => {
    const count = Number(this.element.textContent);
    if (this.element.classList.contains('button-like_active')) {
      this.element.textContent = String(count - 1);
    } else {
      this.element.textContent = String(count + 1);
    }

    this.element.classList.toggle('button-like_active');
  };
}
```
Иконку можно вещать на псевдоэлемент, к примеру на button-like::after { content: 'favorite_border' }, а на button-like_active::after { content: 'favorite' } и тогда уже модификатор font_another не нужен. Но если предпочитаешь jQuery то, можешь и на jQuery все делать)
А инициализацию уже делать в отдельном файле, можно файл init.ts создать для этого в папке с блоком, ну и инициализацию можно делать любым удобным способом главное чтобы она была единообразная во всем проекте. К примеру можно создать класс со статическими полями:
```
class ButtonLikeInit {
  static init() {
    const elements = ButtonLikeInit.getElements();
    elements.forEach(ButtonLikeInit.createInstance);
  }

  static createInstance(element: HTMLElement) {
    const buttonLike = new ButtonLike(element);
    buttonLike.init();
  }

  static getElements() {
    return document.querySelectorAll<HTMLElement>('.js-button-like');
  }
}

ButtonLikeInit.init();
```

**Comment by webproject67** [comment]
пока сделал button-link, если правильно понял, создал плагин для jquery, инициализацию в блоке лежит, реализация в lib
[#33](https://github.com/webproject67/Toxin/issues/33) [updated](https://github.com/webproject67/Toxin/pull/42)

**Comment by Azmodan95** [comment]
Ага все хорошо, только насчет расположений не совсем так, в папку lib нужно выносить только сторонние плагины. Это нужно, для того чтобы минимизировать возможность их изменения. Идеальный вариант это установка через npm, в этом случае даже если кто-то что-то и изменит, изменения будут только у него локально. Если же ты реализовал функционал для какого-то блока, то его выносить отдельно не нужно, так как это часть блока.

**Comment by webproject67** [comment]
[#33](https://github.com/webproject67/Toxin/issues/33) [updated](https://github.com/webproject67/Toxin/pull/43)

**Comment by Azmodan95** [comment]
Файлы с инициализацией нужно называть единообразно, можно просто init.js назвать.

**Comment by webproject67** [comment]
[#33](https://github.com/webproject67/Toxin/issues/33) [updated](https://github.com/webproject67/Toxin/pull/44)

**Comment by Azmodan95** [comment]
Если нужно как-то модифицировать сторонний плагин, эту модификацию нужно выносить в отдельную обертку, так как в противном случае нам при каждой инициализации нужно будет дублировать эту логику. Сейчас это к примеру происходит в  блоке рейтинга и в календаре, можно создавать обертки по такому же принципе как ты делал и свои плагины, обертка будет принимать элемент для которого нужно будет добавить логику, затем производить инициализацию стороннего плагина и какую-то модификацию.

**Comment by webproject67** [comment]
пока только рейтинг, если правильно понял
[#33](https://github.com/webproject67/Toxin/issues/33) [updated](https://github.com/webproject67/Toxin/pull/49)

**Comment by Azmodan95** [comment]
Да все верно

**Comment by webproject67** [comment]
[#33](https://github.com/webproject67/Toxin/issues/33) [updated](https://github.com/webproject67/Toxin/pull/50)
