### ISSUE TITLE
Блок button

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Toxin#37]
Сейчас нет возможности создать просто кнопку, в макете представлены элементы которые могут быть как кнопкой так и ссылкой, но сейчас есть возможно создать только ссылку.

**Comment by webproject67** [comment]
Я читал материал Вадим Макеев "ссылка или кнопка". Всегда кнопка, если не хватает что-то, например, переход на другой адрес, то ссылка, я сделал так, если есть href, то ссылка, если нет, то кнопка

**Comment by Azmodan95** [comment]
От куда такое предположение в form elements именно ссылки, они предполагают куда-то переход? Тут вопрос в том почему нельзя создать обычную кнопку? Исходя из макетов нельзя с уверенностью сказать что там везде ссылки, это все таки учебные макеты и они так детально не проработаны. К примеру в шапке элементы "Войти" и "Зарегистрироваться", могут интерпретироваться как ссылка так и кнопка, тут все зависит от логики реализации в одном случае они могут открывать новую страницу в другом открывать попап. И это довольно-таки странно элементы которые могут выступать и тем и тем, представлены только в одном виде. Даже если из текущих макетов они будут использоваться только в виде ссылок, должна быть возможность создать и то и то, так как кнопка это достаточно часто используемый элемент, и в какой-то момент может понадобиться создать кнопку, а не ссылку или наоборот.

**Comment by webproject67** [comment]
[#37](https://github.com/webproject67/Toxin/issues/37) [updated](https://github.com/webproject67/Toxin/pull/40)

**Comment by Azmodan95** [comment]
Так почему-то теперь вообще абсолютно все кнопки в одном месте, так в макете есть 2 вида кнопок это с заливкой и с рамкой и кнопка с заливкой имеет варианта с иконой, но используются по всему сайту и могут быть как ссылкой, так и кнопкой, это просто элементы без какой-либо логики и внешне они схожи. Рейтинг и кнопка лайка это концептуальные совершенно другие элементы, как минимум они уже выглядят совершенно по другому и наделены какой-то логикой. Они соответственно должны находится в других блоках.
Так же если блок называется button то миксин и классы должны так же называться button. Еще есть проблема с типом, в формах должна быть не ссылка, а кнопка типа submit, если нужно настроить переход на другую страницу то можно использовать свойство action у формы.

**Comment by webproject67** [comment]
[#37](https://github.com/webproject67/Toxin/issues/37) [updated](https://github.com/webproject67/Toxin/pull/45)
