### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Toxin#46]
Сейчас сделан layout который формирует структуру страницы и добавляет head, все хорошо. Но head почему-то сделан отдельным блоком, блок подразумевает переиспользуемость и не только в рамках одного проекта, сложно представить чтобы head вообще мог быть переиспользован на разных страницах, а тем более в других проектах, безусловно если рассматривать его в одном проекте будут схожие вещи вроде каки-то атрибутов и фавиконки. Так вот лучше head убрать из блоков и перенести в layout, ну и можно добавить возможно управлять его содержимым к примеру можно добавить block variables, а на страницах уже можно будет добавлять в него какие-то значения к примеру значение заголовка страницы 
```
block variables
  - const title = '...';
```
Так же желательно в layout добавить header и footer, и между ними вставлять уже контент, но тут уточню их стоит оставить в качестве блоков. Для ui-kit можно создать отдельный layout

---

И еще момент зачем в head дополнительно подключаются шрифты? Они ведь и так подключаются в css через font-face

**Comment by webproject67** [comment]
По-моему в документаций пример смотрел или где-то, head отдельно, в общем перенес в layout.
В head дополнительно подключил шрифты, типа приоритет, в начале html грузится, потом шрифты, затем css, js, в общем убрал, это лишнее)
[#46](https://github.com/webproject67/Toxin/issues/46) [updated](https://github.com/webproject67/Toxin/pull/47)
