### ISSUE TITLE
Блок footer

### ISSUE THREAD

**Issue by osyka-yuri** [webproject67/Toxin#58]
https://github.com/webproject67/Toxin/blob/c346bef4e9fae19d9e1ef47aaf0518af2b555d9a/src/pug/blocks/footer/footer.pug#L12
Почему не через параметры миксина передается значение?
https://github.com/webproject67/Toxin/blob/c346bef4e9fae19d9e1ef47aaf0518af2b555d9a/src/pug/blocks/footer-reduction/footer-reduction.pug#L2
Здесь почему-то миксин называется footer-reduction, а блок page-footer

**Comment by webproject67** [comment]
[#58](https://github.com/webproject67/Toxin/issues/58) [updated](https://github.com/webproject67/Toxin/pull/62)
