### ISSUE TITLE
Сборка

### ISSUE THREAD

**Issue by sodiqit** [webproject67/Toxin#73]
проект не собирается
![image](https://user-images.githubusercontent.com/47000555/147536956-649d4176-6a3a-4156-bfe3-9deca191da4d.png)

**Comment by webproject67** [comment]
странно, удалил папку node_modules, ввел команду:
- npm i - установка
- npm run build - компиляция
- npm run start - запуск
все ок, работает, ошибки нету
установлен windows 7, node v12.22.4, npm 6.14.14
