### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by sodiqit** [webproject67/Toxin#75]
вся подключаемая статика должна быть в формате `lower-case-hyphenated`. Сейчас у некоторых иконок неправильное название, и у шрифтов.

**Comment by sodiqit** [comment]
дай более осмысленные названия. Что делает календарь 3? Чем он отличается от второго? А от первого? Чтобы узнать нужно лезть глубоко в код
![image](https://user-images.githubusercontent.com/47000555/147539630-807cd243-4d24-4309-9dbf-9658f6e88ed4.png)

**Comment by webproject67** [comment]
[#75](https://github.com/webproject67/Toxin/issues/75) [updated](https://github.com/webproject67/Toxin/pull/78)
