### ISSUE TITLE
Файловая структура 

### ISSUE THREAD

**Issue by sodiqit** [webproject67/Toxin#76]
не понял зачем нужна папка docs? в чем отличие от public? можно вообще убрать одну из них(я предполагаю папку docs), а public в гитигнор закинуть

**Comment by webproject67** [comment]
![Снимок](https://user-images.githubusercontent.com/34152979/147600754-6775b133-3169-4be7-bdee-49d152130914.PNG)
---
переименовал public на docs, папка docs необходим для Github Pages.
[#76](https://github.com/webproject67/Toxin/issues/76) [updated](https://github.com/webproject67/Toxin/pull/79)
