### ISSUE TITLE
Семантика

### ISSUE THREAD

**Issue by sodiqit** [webproject67/Toxin#77]
Тут нужен список
![image](https://user-images.githubusercontent.com/47000555/147538412-464f79af-6bd2-419e-883d-c34f6d337dda.png)
Прогляди по проекту, мб где-то еще такие места есть

**Comment by sodiqit** [comment]
Почему в форме тип у кнопки `button`?
![image](https://user-images.githubusercontent.com/47000555/147539536-bd831332-b6a1-4e6d-8db4-5f30db0ad443.png)

**Comment by webproject67** [comment]
[#77](https://github.com/webproject67/Toxin/issues/77) [updated](https://github.com/webproject67/Toxin/pull/80)
