### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by sodiqit** [webproject67/Toxin#81]
есть баг с дропдауном с выбором удобств. 
![image](https://user-images.githubusercontent.com/47000555/149616148-85f250a3-4e45-44e8-b958-687adf376de5.png)

Также когда выбирается две позиции то ставится `...`, такого по идее быть не должно, троеточие означает что в поле ввода есть что-то есть кроме спален и кроватей, как в этом случае допустим.
![image](https://user-images.githubusercontent.com/47000555/149616182-f8c3d2e8-ed30-444c-bfa3-183c32944071.png)

**Comment by webproject67** [comment]
![Снимок](https://user-images.githubusercontent.com/34152979/149626103-7dcf42ae-3756-4097-812e-384526c058c7.PNG)
это не баг, так задумано, верстал как в макете,  видимо дизайнер не учел, в общем исправил)
[#81](https://github.com/webproject67/Toxin/issues/81) [updated](https://github.com/webproject67/Toxin/pull/82)
