### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Toxin#9]
Убери `package-lock.json` из `.gitignore` (тем более что этот файл уже отслеживается).

https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by romansilivestrov** [comment]
Файлы в папке `public` также уже отслеживается, соответственно непонятно, зачем добавлять её `.gitignore`.

**Comment by webproject67** [comment]
[#9](https://github.com/webproject67/Toxin/issues/9) [updated](https://github.com/webproject67/Toxin/pull/13)
